/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ai.ocrstudio.sdk;

import ai.ocrstudio.sdk.*;

public class OCRStudioSDKResult {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public OCRStudioSDKResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(OCRStudioSDKResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jniocrstudiosdkJNI.delete_OCRStudioSDKResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OCRStudioSDKResult DeepCopy() {
    long cPtr = jniocrstudiosdkJNI.OCRStudioSDKResult_DeepCopy(swigCPtr, this);
    return (cPtr == 0) ? null : new OCRStudioSDKResult(cPtr, true);
  }

  public int TargetsCount() {
    return jniocrstudiosdkJNI.OCRStudioSDKResult_TargetsCount(swigCPtr, this);
  }

  public OCRStudioSDKTarget TargetByIndex(int target_index) {
    return new OCRStudioSDKTarget(jniocrstudiosdkJNI.OCRStudioSDKResult_TargetByIndex(swigCPtr, this, target_index), false);
  }

  public boolean AllTargetsFinal() {
    return jniocrstudiosdkJNI.OCRStudioSDKResult_AllTargetsFinal(swigCPtr, this);
  }

}
